<?php

/**
 * super globals
 */
$fields_array = array(FIELD_BREWERY_NAME, FIELD_BREWERY_FB, FIELD_BREWERY_INSTAGRAM, FIELD_BREWERY_TWITTER, FIELD_BREWERY_WEB, FIELD_BREWERY_MAIL, FIELD_BREWERY_PHONE, FIELD_BREWERY_ADDRESS, FIELD_BREWERY_UNTAPPD, FIELD_BREWERY_RATEBEER);
$url_fields_array = array(FIELD_BREWERY_FB, FIELD_BREWERY_INSTAGRAM, FIELD_BREWERY_TWITTER, FIELD_BREWERY_WEB, FIELD_BREWERY_UNTAPPD, FIELD_BREWERY_RATEBEER);
